version: "3.8"

services:
  # Apache Spark Master
  spark-master:
    image: bitnami/spark:3.5.0
    container_name: kanizsa-spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    restart: unless-stopped
    networks:
      - kanizsa-analytics

  # Apache Spark Worker
  spark-worker:
    image: bitnami/spark:3.5.0
    container_name: kanizsa-spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    restart: unless-stopped
    networks:
      - kanizsa-analytics

  # Apache Flink JobManager
  flink-jobmanager:
    image: apache/flink:1.18.1
    container_name: kanizsa-flink-jobmanager
    ports:
      - "8081:8081"
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address:flink-jobmanager
    command: jobmanager
    restart: unless-stopped
    networks:
      - kanizsa-analytics

  # Apache Flink TaskManager
  flink-taskmanager:
    image: apache/flink:1.18.1
    container_name: kanizsa-flink-taskmanager
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address:flink-jobmanager;taskmanager.numberOfTaskSlots:2
    depends_on:
      - flink-jobmanager
    command: taskmanager
    restart: unless-stopped
    networks:
      - kanizsa-analytics

  # ClickHouse - Analytics database
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: kanizsa-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=kanizsa_analytics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse_password
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./config/clickhouse:/etc/clickhouse-server/config.d
    restart: unless-stopped
    networks:
      - kanizsa-analytics

  # Analytics API
  analytics-api:
    build: .
    container_name: kanizsa-analytics-api
    ports:
      - "8000:8000"
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - FLINK_JOBMANAGER_URL=http://flink-jobmanager:8081
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    depends_on:
      - spark-master
      - flink-jobmanager
      - clickhouse
    restart: unless-stopped
    networks:
      - kanizsa-analytics

volumes:
  clickhouse_data:

networks:
  kanizsa-analytics:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
